export const LOGIN_FORM_TITLE = 'Login'
export const LOGIN_FORM_BUTTON_TEXT = 'Login'
export const LOGIN_FORM_USERNAME = 'Username'
export const LOGIN_FORM_USERNAME_PLACEHOLDER = 'jane@doe.com'
export const LOGIN_FORM_PASSWORD = 'Password'
